services:
  database:
    image: postgres:16-alpine
    container_name: portfolio_db
    restart: always
    env_file: .env
    environment:
      # Te zmienne Docker wykorzystuje do stworzenia bazy i superusera przy starcie
      - POSTGRES_USER=${DB_ADMIN_USER}
      - POSTGRES_PASSWORD=${DB_ADMIN_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ${DB_STORAGE_PATH}:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_ADMIN_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5